name: worldcereal
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pytorch=2.10.*
  - python=3.11.*
  - pip:
    - worldcereal[train,notebooks] @ git+https://github.com/worldcereal/worldcereal-classification